MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnext_backbone #build_resnet_backbone
    NORM: BN
    DEPTH: 101x #50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    PRETRAIN: True

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: GlobalAvgPool
    NECK_FEAT: before
    CLS_LAYER: Linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "CircleLoss","TripletLoss")  #("CrossEntropyLoss", "TripletLoss",) 

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [ 256, 256 ]
  SIZE_TEST: [ 256, 256 ]

  REA:
    ENABLED: True
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True
  #CROP:
  #  ENABLED: True
  #  SCALE: [0.5,1]
  #do_crop = cfg.INPUT.CROP.ENABLED
  #      crop_size = cfg.INPUT.CROP.SIZE
  #      crop_scale = cfg.INPUT.CROP.SCALE
  #      crop_ratio = cfg.INPUT.CROP.RATIO
  AFFINE:
    ENABLED : True

  AUTOAUG:
    ENABLED : True
    PROB : 0.5
  CJ:
    ENABLED : True
    PROB : 0.4
    BRIGHTNESS : 0.35

  RPT:
    ENABLED : True
    PROB : 0.1

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 1

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 8 #64

  SCHED: CosineAnnealingLR #MultiStepLR
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 64  #128

CUDNN_BENCHMARK: True
